### ISSUE TITLE
Cannot Parse the supplied time format issue

### ISSUE THREAD

**Issue by Sambit78** [JosiahParry/trendyy#5]
Hi , 

I was playing with the trendyy package for few hours and it was working fine. It has suddenly started putting out the error message on time format.

The code I am using is fairly straightforward.

analytics <- c("salvos")
analytics_trends <- trendy(analytics, from = "2016-01-01", to = Sys.Date())

**Comment by JosiahParry** [comment]
Hi @Sambit78 can you be more specific and show the error that you are encountering? I have no problem running the above code.

``` r
analytics <- c("salvos")
analytics_trends <- trendyy::trendy(analytics, from = "2016-01-01", to = Sys.Date())

analytics_trends
#> ~Trendy results~
#> 
#> Search Terms: salvos
#> 
#> (>^.^)> ~~~~~~~~~~~~~~~~~~~~ summary ~~~~~~~~~~~~~~~~~~~~ <(^.^<)
#> # A tibble: 1 x 5
#>   keyword max_hits min_hits from       to        
#>   <chr>      <dbl>    <dbl> <date>     <date>    
#> 1 salvos       100       61 2016-01-03 2019-05-26
```

<sup>Created on 2019-06-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Sambit78** [comment]
Hi @JosiahParry . 

Thank you for your quick reply
Here is the full code 

#install.packages("trendyy")
#remotes::install_github("josiahparry/gtrendsR", "interest_refactor")
library(trendyy)
library(dplyr)
library(ggplot2)

# http://josiahparry.com/post/2019-05-25-introducing-trendyy/


# 1. Create Vector for search terms ----
analytics <-  c("virat kohli","steve smith")
# 2. Get Query ----
analytics_trends <- trendy(analytics, from = "2016-01-01", to = Sys.Date())

# 3. Get Summary of trends ----
analytics_trends

Here is a screenshot of the error message

<img width="895" alt="Screen Shot 2019-06-02 at 10 38 41 am" src="https://user-images.githubusercontent.com/30438293/58755227-9cf20600-8522-11e9-95a9-7d4042c3b459.png">

**Comment by Sambit78** [comment]
Hi @JosiahParry : I cleared the cache of the global environment and ran again. It is working now. Not sure why it happened in the first place :)

Thanks anyways.
Cheers
Sambit
