### ISSUE TITLE
Add "topic suggestions" 

### ISSUE THREAD

**Issue by patarol** [JosiahParry/trendyy#6]
I'm using `trendyy` package very often lately. This is a very nice package and I love the tidy workflow you've programmed it. 
There's a `python` library, `pytrends` and they have a nice feature, which is [suggestions](https://github.com/GeneralMills/pytrends/blob/b22c61810bfbb63d917c7db8b47ee134601f2ee3/README.md#suggestions). With suggestions you type a search term and it suggests another related search term (it can be a translation to English or whatever).

**Comment by JosiahParry** [comment]
It looks like the `pytrends` package is using the same data sources as `gtrendsR` and thereby `trendyy`. Have you tried the `get_related_queries()` and `get_related_topics()` functions? This might fit your use case.
